# Generated by Django 5.0.6 on 2024-06-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_api_apimodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimodel',
            name='img',
            field=models.ImageField(default=1, max_length=300, upload_to=''),
            preserve_default=False,
        ),
    ]
