# Generated by Django 5.0.6 on 2024-06-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_apimodel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimodel',
            name='nomer',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
